# Generated by Django 4.2.3 on 2023-08-03 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformcontent',
            name='platform_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='platformcontent',
            name='platform_type',
            field=models.CharField(blank=True, choices=[('Y', 'YouTube'), ('T', 'Twitch')], default='', max_length=1),
        ),
    ]
