# Generated by Django 4.2.3 on 2023-08-03 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platformcontent',
            name='platform_type',
        ),
    ]
