# Generated by Django 4.2.3 on 2023-08-04 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='deal',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
