# Generated by Django 4.2.3 on 2023-08-04 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='platform_username',
            field=models.CharField(blank=True, default='', max_length=50),
            preserve_default=False,
        ),
    ]
