# Generated by Django 4.2.3 on 2023-08-04 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='deal',
        ),
        migrations.AddField(
            model_name='deal',
            name='activities',
            field=models.ManyToManyField(to='main_app.activity'),
        ),
    ]
