# Generated by Django 4.2.3 on 2023-08-01 16:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_deal_amount_alter_deal_details_alter_deal_done_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='create_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
