# Generated by Django 4.2.3 on 2023-08-01 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_deal_amount_alter_deal_create_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='done',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
