# Generated by Django 4.2.3 on 2023-08-04 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_activity_deal_deal_activities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal',
            name='activities',
        ),
        migrations.AddField(
            model_name='activity',
            name='deal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.deal'),
            preserve_default=False,
        ),
    ]
