# Generated by Django 4.2.3 on 2023-08-02 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_platformcontent_alter_deal_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deal',
            old_name='create_date',
            new_name='created_date',
        ),
    ]
