# Generated by Django 4.2.3 on 2023-08-02 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_platform_content_alter_deal_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='platforms_content',
            field=models.ManyToManyField(to='main_app.platform_content'),
        ),
    ]
