# Generated by Django 4.2.3 on 2023-08-02 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_deal_create_date'),
        ('main_app', '0003_alter_deal_done'),
    ]

    operations = [
    ]
