# Generated by Django 4.2.3 on 2023-08-02 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_deal_platforms_content'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Platform_content',
            new_name='PlatformContent',
        ),
        migrations.RenameField(
            model_name='deal',
            old_name='platforms_content',
            new_name='platformsContent',
        ),
    ]
