# Generated by Django 4.2.3 on 2023-08-02 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_rename_platform_content_platformcontent_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deal',
            old_name='platformsContent',
            new_name='platformscontent',
        ),
    ]
